# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build options
build:
  os: ubuntu-24.04
  tools:
    python: "3.10"
  jobs:
    post_build:
      - zensical build
      - mkdir -p $READTHEDOCS_OUTPUT/html/
      - cp -r docs/_build/zensical/* $READTHEDOCS_OUTPUT/html/

# Install the package
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
