name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release-pypi:
    name: Release to PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get current git tag
        id: tag
        run: |
          TAG=$(git describe --tags --abbrev=0)
          # Remove the leading 'v' from the tag (e.g., 'v1.2.3' -> '1.2.3')
          GIT_VERSION=${TAG#v}
          echo "Current git tag version: $GIT_VERSION"
          echo "::set-output name=tag::$GIT_VERSION"

      - name: Check if git tag matches version
        run: |
          # Extract version from pyproject.toml
          PY_VERSION=$(grep '^version = "' pyproject.toml | sed 's/version = "\(.*\)"/\1/')
          echo "Version from pyproject.toml: $PY_VERSION"
          if [ "$PY_VERSION" != "${{ steps.tag.outputs.tag }}" ]; then
            echo "Git tag does not match version in pyproject.toml."
            exit 1
          else
            echo "Git tag matches version in pyproject.toml."
          fi

      - name: Setup Rye
        uses: eifinger/setup-rye@v4

      - name: Build wheels
        run: |
          rye build

      - name: Test build
        run: |
          python3 -m venv fresh_env
          . fresh_env/bin/activate
          pip install dist/*.whl
          fresh_env/bin/python -c "import xarray_validate; print(xarray_validate.__version__)"

      - name: Upload to PyPI
        run: |
          rye publish --token ${{ secrets.PYPI_TOKEN }} --yes
